[General]
font=Noto Sans,10,-1,5,50,0,0,0,0,0
fixed=Terminus,12,-1,5,50,0,0,0,0,0
menuFont=Terminus,10,-1,5,50,0,0,0,0,0
smallestReadableFont=Noto Sans,8,-1,5,50,0,0,0,0,0
toolBarFont=Terminus,10,-1,5,50,0,0,0,0,0

[WM]
activeFont=Terminus,11,-1,5,50,0,0,0,0,0
