[General]
font=Noto Sans,10,-1,5,50,0,0,0,0,0
fixed=Noto Sans Mono,10,-1,5,50,0,0,0,0,0
menuFont=Noto Sans Mono,9,-1,5,50,0,0,0,0,0
smallestReadableFont=Noto Sans,8,-1,5,50,0,0,0,0,0
toolBarFont=Noto Sans Mono,9,-1,5,50,0,0,0,0,0

[WM]
activeFont=Noto Sans Mono,10,-1,5,50,0,0,0,0,0
