#!/bin/sh
set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-image iso-hybrid \
    --bootloaders "grub-efi syslinux" \
    --uefi-secure-boot enable \
    --debian-installer none \
    --apt-recommends true \
    --memtest none \
    --iso-application "MARISHOKU/OS Live" \
    --iso-publisher "Eclipxse" \
    --iso-volume "MARISHOKU_V1_3" \
    --image-name "marishoku-os-v1.3-amd64" \
    --bootappend-live "boot=live components quiet splash username=mario hostname=marishoku locales=en_US.UTF-8 keyboard-layouts=us" \
    "${@}"
